{
  "chaoslib-version": "1.19.0",
  "platform": "Linux-5.8.0-48-generic-x86_64-with-glibc2.29",
  "node": "luisreciomelero-HP-Pavilion-Laptop-15-ck0xx",
  "experiment": {
    "version": "1.0.0",
    "title": "¿Qué ocurre cuando eliminamos el deployment que gestiona el microservicio create?",
    "description": "Observamos como reacciona nuestro cluster al eliminar el deployment",
    "tags": [
      "k8s",
      "deployment"
    ],
    "method": [
      {
        "name": "create-deployment",
        "provider": {
          "arguments": {
            "spec_path": "/home/luisreciomelero/Escritorio/TFM/TFM/kubernetes-stack/yamls-pre-chaos/crud-app/ms-create.yaml"
          },
          "func": "create_deployment",
          "module": "chaosk8s.deployment.actions",
          "type": "python"
        },
        "ns": "default",
        "type": "action"
      }
    ],
    "dry": false
  },
  "start": "2021-04-11T14:15:05.512472",
  "status": "completed",
  "deviated": false,
  "steady_states": {
    "before": null,
    "after": null,
    "during": []
  },
  "run": [
    {
      "activity": {
        "name": "create-deployment",
        "provider": {
          "arguments": {
            "spec_path": "/home/luisreciomelero/Escritorio/TFM/TFM/kubernetes-stack/yamls-pre-chaos/crud-app/ms-create.yaml"
          },
          "func": "create_deployment",
          "module": "chaosk8s.deployment.actions",
          "type": "python"
        },
        "ns": "default",
        "type": "action"
      },
      "output": null,
      "status": "failed",
      "exception": [
        "Traceback (most recent call last):\n",
        "  File \"/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py\", line 55, in run_python_activity\n    return func(**arguments)\n",
        "  File \"/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py\", line 29, in create_deployment\n    deployment = yaml.load(f.read())\n",
        "  File \"/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/__init__.py\", line 114, in load\n    return loader.get_single_data()\n",
        "  File \"/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/constructor.py\", line 49, in get_single_data\n    node = self.get_single_node()\n",
        "  File \"/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/composer.py\", line 41, in get_single_node\n    raise ComposerError(\"expected a single document in the stream\",\n",
        "yaml.composer.ComposerError: expected a single document in the stream\n  in \"<unicode string>\", line 2, column 1:\n    apiVersion: apps/v1\n    ^\nbut found another document\n  in \"<unicode string>\", line 52, column 1:\n    ---\n    ^\n",
        "\nDuring handling of the above exception, another exception occurred:\n\n",
        "chaoslib.exceptions.ActivityFailed: yaml.composer.ComposerError: expected a single document in the stream\n  in \"<unicode string>\", line 2, column 1:\n    apiVersion: apps/v1\n    ^\nbut found another document\n  in \"<unicode string>\", line 52, column 1:\n    ---\n    ^\n"
      ],
      "start": "2021-04-11T14:15:05.513020",
      "end": "2021-04-11T14:15:05.522844",
      "duration": 0.009824
    }
  ],
  "rollbacks": [],
  "end": "2021-04-11T14:15:05.523212",
  "duration": 0.018878459930419922
}