[36m[2021-04-10 13:21:41 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-10 13:21:41 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-10 13:21:41 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-10 13:21:42 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-10 13:21:42 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:21:42 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:21:42 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:21:42 DEBUG] [caching:35][39m Cached 4 activities
[32m[2021-04-10 13:21:42 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-10 13:21:42 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:21:42 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:21:42 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:21:43 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-10 13:21:43 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:21:43 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:21:43 DEBUG] [caching:35][39m Cached 4 activities
[36m[2021-04-10 13:21:43 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:21:43 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:21:43 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:21:43 INFO] [run:323][39m Running experiment: What happens if we terminate a Pod?
[36m[2021-04-10 13:21:43 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-10 13:21:43 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-10 13:21:43 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-10 13:21:43 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:21:43 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-10 13:21:43 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:21:43 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:21:43 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:21:43 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:21:43 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:21:43 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:21:44 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:21:44 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:21:44 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:21:44 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:21:44 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:21:44 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:21:44 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:21:44 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:21:44 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:21:44 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:21:44 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:21:44 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:21:44 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:21:44 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:21:44 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:21:44 INFO] [activity:161][39m Action: terminate-pod
[36m[2021-04-10 13:21:44 DEBUG] [python:34][39m Activity 'terminate-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-04-10 13:21:44 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:21:44 DEBUG] [actions:193][39m Found 1 pods labelled 'app=crud-app, component=ms-create' in ns default
[36m[2021-04-10 13:21:44 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-04-10 13:21:44 INFO] [activity:198][39m Pausing after activity for 40s...
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:22:24 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-10 13:22:24 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:22:24 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:22:24 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:22:24 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:22:24 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:22:24 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:22:24 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:22:24 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:22:24 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:22:24 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:22:24 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:22:24 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:22:24 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:22:24 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:22:24 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:22:24 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:22:24 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-mhb4n does not match the following given condition: {'type': 'Ready', 'status': 'True'}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-mhb4n does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[31m[2021-04-10 13:22:25 ERROR] [activity:188][39m   => failed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-mhb4n does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[36m[2021-04-10 13:22:25 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[33m[2021-04-10 13:22:25 WARNING] [hypothesis:200][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2021-04-10 13:22:25 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[31m[2021-04-10 13:22:25 CRITICAL] [run:507][39m Steady state probe 'pod-in-conditions' is not in the given tolerance so failing this experiment
[32m[2021-04-10 13:22:25 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-10 13:22:25 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-10 13:22:25 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:22:25 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-10 13:22:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:24:52 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-10 13:24:52 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-10 13:24:52 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-10 13:24:53 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:24:53 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:24:53 DEBUG] [caching:35][39m Cached 4 activities
[32m[2021-04-10 13:24:53 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-10 13:24:53 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:24:53 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:24:53 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:24:53 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-10 13:24:53 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:24:53 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:24:53 DEBUG] [caching:35][39m Cached 4 activities
[36m[2021-04-10 13:24:53 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:24:53 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:24:53 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:24:53 INFO] [run:323][39m Running experiment: What happens if we terminate a Pod?
[36m[2021-04-10 13:24:53 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-10 13:24:53 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-10 13:24:53 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:24:53 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-10 13:24:53 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:24:53 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:24:53 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:24:53 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:24:53 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:24:53 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:24:53 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:24:53 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:24:53 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:24:53 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:24:53 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:24:53 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:24:53 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:24:53 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:24:53 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:24:53 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:24:53 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:24:53 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:24:53 INFO] [activity:161][39m Action: terminate-pod
[36m[2021-04-10 13:24:53 DEBUG] [python:34][39m Activity 'terminate-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-04-10 13:24:53 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:24:53 DEBUG] [actions:193][39m Found 1 pods labelled 'app=crud-app, component=ms-create' in ns default
[36m[2021-04-10 13:24:53 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-04-10 13:24:53 INFO] [activity:198][39m Pausing after activity for 80s...
[36m[2021-04-10 13:26:13 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:26:13 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:26:13 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-10 13:26:13 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:26:13 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:26:13 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:26:13 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:26:13 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:26:14 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:26:18 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:26:18 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:26:18 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:26:18 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:26:18 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:26:18 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:26:18 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:26:18 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:26:21 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:26:21 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:26:21 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:26:21 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:26:21 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:26:21 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:26:21 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:26:21 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:26:22 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:26:22 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-pn775 does not match the following given condition: {'type': 'Ready', 'status': 'True'}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-pn775 does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[31m[2021-04-10 13:26:23 ERROR] [activity:188][39m   => failed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-pn775 does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[36m[2021-04-10 13:26:23 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[33m[2021-04-10 13:26:23 WARNING] [hypothesis:200][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2021-04-10 13:26:23 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[31m[2021-04-10 13:26:23 CRITICAL] [run:507][39m Steady state probe 'pod-in-conditions' is not in the given tolerance so failing this experiment
[32m[2021-04-10 13:26:23 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-10 13:26:23 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-10 13:26:23 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:26:23 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-10 13:26:23 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:28:43 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-10 13:28:43 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-10 13:28:43 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-10 13:28:44 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-10 13:28:44 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:28:44 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:28:44 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:28:44 DEBUG] [caching:35][39m Cached 4 activities
[32m[2021-04-10 13:28:44 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-10 13:28:44 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:28:44 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:28:44 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:28:47 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-10 13:28:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:28:47 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:28:47 DEBUG] [caching:35][39m Cached 4 activities
[36m[2021-04-10 13:28:47 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:28:47 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:28:47 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:28:47 INFO] [run:323][39m Running experiment: What happens if we terminate a Pod?
[36m[2021-04-10 13:28:47 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-10 13:28:47 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-10 13:28:47 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:28:47 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-10 13:28:47 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:28:47 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:28:47 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:28:47 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:28:47 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:28:47 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:28:47 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:28:47 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:28:47 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:28:47 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:28:47 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:28:47 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:28:47 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:28:47 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:28:47 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:28:47 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:28:47 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:28:47 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:28:47 INFO] [activity:161][39m Action: terminate-pod
[36m[2021-04-10 13:28:47 DEBUG] [python:34][39m Activity 'terminate-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-04-10 13:28:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:28:47 DEBUG] [actions:193][39m Found 1 pods labelled 'app=crud-app, component=ms-create' in ns default
[36m[2021-04-10 13:28:47 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-04-10 13:28:47 INFO] [activity:198][39m Pausing after activity for 120s...
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:30:47 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-10 13:30:47 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:30:47 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:30:47 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:30:47 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:30:47 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:30:47 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:30:47 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:30:47 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:30:47 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:30:47 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:30:47 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:30:47 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:30:47 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:30:47 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:30:47 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-2lf2f does not match the following given condition: {'type': 'Ready', 'status': 'True'}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-2lf2f does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[31m[2021-04-10 13:30:47 ERROR] [activity:188][39m   => failed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-2lf2f does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[33m[2021-04-10 13:30:47 WARNING] [hypothesis:200][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[31m[2021-04-10 13:30:47 CRITICAL] [run:507][39m Steady state probe 'pod-in-conditions' is not in the given tolerance so failing this experiment
[32m[2021-04-10 13:30:47 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-10 13:30:47 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-10 13:30:47 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:30:47 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-10 13:30:47 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:36:50 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-10 13:36:50 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-10 13:36:50 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-10 13:36:51 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-10 13:36:51 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:36:51 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:36:51 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:36:51 DEBUG] [caching:35][39m Cached 4 activities
[32m[2021-04-10 13:36:51 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-10 13:36:51 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:36:51 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:36:51 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:36:56 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-10 13:36:56 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:36:56 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:36:56 DEBUG] [caching:35][39m Cached 4 activities
[36m[2021-04-10 13:36:56 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:36:56 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:36:56 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:36:56 INFO] [run:323][39m Running experiment: What happens if we terminate a Pod?
[36m[2021-04-10 13:36:56 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-10 13:36:56 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-10 13:36:56 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:36:56 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-10 13:36:56 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:36:56 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:36:56 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:36:56 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:36:56 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:36:56 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:36:56 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:36:56 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:36:56 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:36:56 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:36:56 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:36:56 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:36:56 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:36:56 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:36:56 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:36:56 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:36:56 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:36:56 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:36:56 INFO] [activity:161][39m Action: terminate-pod
[36m[2021-04-10 13:36:56 DEBUG] [python:34][39m Activity 'terminate-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-04-10 13:36:56 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:36:56 DEBUG] [actions:193][39m Found 1 pods labelled 'app=crud-app, component=ms-create' in ns default
[36m[2021-04-10 13:36:56 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-04-10 13:36:56 INFO] [activity:198][39m Pausing after activity for 150s...
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:39:27 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-10 13:39:27 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:39:27 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:39:27 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:39:27 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:39:27 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:39:27 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:39:27 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:39:27 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:39:27 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:39:27 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:39:27 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:39:27 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:39:27 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:39:27 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:39:27 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:39:27 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:39:27 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-lzn2d does not match the following given condition: {'type': 'Ready', 'status': 'True'}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py", line 149, in pods_in_conditions
        raise ActivityFailed("pod {name} does not match the following "
    chaoslib.exceptions.ActivityFailed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-lzn2d does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[31m[2021-04-10 13:39:28 ERROR] [activity:188][39m   => failed: chaoslib.exceptions.ActivityFailed: pod ms-create-depl-5f7d6d568-lzn2d does not match the following given condition: {'type': 'Ready', 'status': 'True'}
[36m[2021-04-10 13:39:28 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[33m[2021-04-10 13:39:28 WARNING] [hypothesis:200][39m Probe terminated unexpectedly, so its tolerance could not be validated
[36m[2021-04-10 13:39:28 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[31m[2021-04-10 13:39:28 CRITICAL] [run:507][39m Steady state probe 'pod-in-conditions' is not in the given tolerance so failing this experiment
[32m[2021-04-10 13:39:28 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-10 13:39:28 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-10 13:39:28 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:39:28 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-10 13:39:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:40:35 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-10 13:40:35 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-10 13:40:35 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-10 13:40:36 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-10 13:40:36 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:40:36 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-10 13:40:36 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:40:36 DEBUG] [caching:35][39m Cached 4 activities
[32m[2021-04-10 13:40:36 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-10 13:40:36 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:40:36 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:40:36 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:40:39 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-10 13:40:39 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-10 13:40:39 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-10 13:40:39 DEBUG] [caching:35][39m Cached 4 activities
[36m[2021-04-10 13:40:39 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-10 13:40:39 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-10 13:40:39 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-10 13:40:39 INFO] [run:323][39m Running experiment: What happens if we terminate a Pod?
[36m[2021-04-10 13:40:39 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-10 13:40:39 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-10 13:40:39 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:40:39 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-10 13:40:39 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:40:39 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:40:39 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:40:39 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:40:39 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:40:39 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:40:39 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:40:39 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:40:39 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:40:39 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:40:39 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:40:39 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:40:39 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:40:39 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:40:39 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:40:39 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:40:39 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:40:39 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:40:39 INFO] [activity:161][39m Action: terminate-pod
[36m[2021-04-10 13:40:39 DEBUG] [python:34][39m Activity 'terminate-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-04-10 13:40:39 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:40:39 DEBUG] [actions:193][39m Found 1 pods labelled 'app=crud-app, component=ms-create' in ns default
[36m[2021-04-10 13:40:39 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-04-10 13:40:39 INFO] [activity:198][39m Pausing after activity for 200s...
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-10 13:43:59 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-10 13:43:59 INFO] [hypothesis:183][39m Steady state hypothesis: Pod exists
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:43:59 INFO] [activity:161][39m Probe: pod-exists
[36m[2021-04-10 13:43:59 DEBUG] [python:34][39m Activity 'pod-exists' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:43:59 DEBUG] [probes:202][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:43:59 DEBUG] [activity:180][39m   => succeeded with '1'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:43:59 DEBUG] [hypothesis:211][39m allowed tolerance is 1
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:43:59 INFO] [activity:161][39m Probe: pod-in-phase
[36m[2021-04-10 13:43:59 DEBUG] [python:34][39m Activity 'pod-in-phase' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:43:59 DEBUG] [probes:97][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:43:59 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:43:59 DEBUG] [hypothesis:211][39m allowed tolerance is True
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-10 13:43:59 INFO] [activity:161][39m Probe: pod-in-conditions
[36m[2021-04-10 13:43:59 DEBUG] [python:34][39m Activity 'pod-in-conditions' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-10 13:43:59 DEBUG] [probes:130][39m Found 1 pods matching label 'app=crud-app, component=ms-create' in ns 'default'
[36m[2021-04-10 13:43:59 DEBUG] [activity:180][39m   => succeeded with 'True'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-10 13:43:59 DEBUG] [hypothesis:211][39m allowed tolerance is True
[32m[2021-04-10 13:43:59 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-04-10 13:43:59 INFO] [run:809][39m Let's rollback...
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-10 13:43:59 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-10 13:43:59 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-10 13:43:59 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-10 13:43:59 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-10 13:43:59 DEBUG] [caching:42][39m Clearing activities cache
