[36m[2021-04-11 16:10:38 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-11 16:10:38 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-11 16:10:38 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-11 16:10:39 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-11 16:10:39 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-11 16:10:39 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-11 16:10:39 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-11 16:10:39 DEBUG] [caching:35][39m Cached 1 activities
[32m[2021-04-11 16:10:39 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-11 16:10:39 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-11 16:10:39 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-11 16:10:39 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-11 16:10:40 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-11 16:10:40 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-11 16:10:40 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-11 16:10:40 DEBUG] [caching:35][39m Cached 1 activities
[36m[2021-04-11 16:10:40 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-11 16:10:40 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-11 16:10:40 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-11 16:10:40 INFO] [run:323][39m Running experiment: Â¿QuÃ© ocurre cuando eliminamos el deployment que gestiona el microservicio create?
[36m[2021-04-11 16:10:40 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-11 16:10:40 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-11 16:10:40 INFO] [run:345][39m Rollbacks strategy: default
[32m[2021-04-11 16:10:40 INFO] [run:350][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[32m[2021-04-11 16:10:40 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-11 16:10:40 INFO] [activity:161][39m Action: create-deployment
[36m[2021-04-11 16:10:40 DEBUG] [python:34][39m Activity 'create-deployment' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py'
[36m[2021-04-11 16:10:40 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-11 16:10:40 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py", line 29, in create_deployment
        deployment = yaml.load(f.read())
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/composer.py", line 41, in get_single_node
        raise ComposerError("expected a single document in the stream",
    yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py", line 29, in create_deployment
        deployment = yaml.load(f.read())
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/composer.py", line 41, in get_single_node
        raise ComposerError("expected a single document in the stream",
    chaoslib.exceptions.ActivityFailed: yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
[31m[2021-04-11 16:10:40 ERROR] [activity:188][39m   => failed: yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'method'
[32m[2021-04-11 16:10:40 INFO] [run:809][39m Let's rollback...
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-11 16:10:40 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-11 16:10:40 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-11 16:10:40 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-11 16:10:40 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-11 16:10:40 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-11 16:15:04 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-11 16:15:04 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-11 16:15:04 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-11 16:15:05 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/home/luisreciomelero/.chaostoolkit/settings.yaml'.
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-04-11 16:15:05 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-11 16:15:05 DEBUG] [caching:35][39m Cached 1 activities
[32m[2021-04-11 16:15:05 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-11 16:15:05 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-11 16:15:05 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-11 16:15:05 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-11 16:15:05 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-11 16:15:05 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-11 16:15:05 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-11 16:15:05 DEBUG] [caching:35][39m Cached 1 activities
[36m[2021-04-11 16:15:05 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-11 16:15:05 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-11 16:15:05 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-11 16:15:05 INFO] [run:323][39m Running experiment: Â¿QuÃ© ocurre cuando eliminamos el deployment que gestiona el microservicio create?
[36m[2021-04-11 16:15:05 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-11 16:15:05 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-11 16:15:05 INFO] [run:345][39m Rollbacks strategy: default
[32m[2021-04-11 16:15:05 INFO] [run:350][39m No steady state hypothesis defined. That's ok, just exploring.
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[32m[2021-04-11 16:15:05 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-04-11 16:15:05 INFO] [activity:161][39m Action: create-deployment
[36m[2021-04-11 16:15:05 DEBUG] [python:34][39m Activity 'create-deployment' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py'
[36m[2021-04-11 16:15:05 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-04-11 16:15:05 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py", line 29, in create_deployment
        deployment = yaml.load(f.read())
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/composer.py", line 41, in get_single_node
        raise ComposerError("expected a single document in the stream",
    yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/deployment/actions.py", line 29, in create_deployment
        deployment = yaml.load(f.read())
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/yaml/composer.py", line 41, in get_single_node
        raise ComposerError("expected a single document in the stream",
    chaoslib.exceptions.ActivityFailed: yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
[31m[2021-04-11 16:15:05 ERROR] [activity:188][39m   => failed: yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 2, column 1:
        apiVersion: apps/v1
        ^
    but found another document
      in "<unicode string>", line 52, column 1:
        ---
        ^
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'method'
[32m[2021-04-11 16:15:05 INFO] [run:809][39m Let's rollback...
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-11 16:15:05 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'rollback'
[32m[2021-04-11 16:15:05 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-11 16:15:05 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-04-11 16:15:05 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-11 16:15:05 DEBUG] [caching:42][39m Clearing activities cache
