[36m[2021-04-12 19:34:02 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-12 19:34:02 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-12 19:34:02 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-12 19:34:03 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-12 19:34:03 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:34:03 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:03 DEBUG] [workspace:85][39m The ChaosIQ workspace file could not be found at '.chaosiq'.
[36m[2021-04-12 19:34:03 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:34:03 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:03 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:34:03 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-12 19:34:03 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-12 19:34:03 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:34:03 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:34:03 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:34:04 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-12 19:34:04 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-12 19:34:04 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:34:04 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-12 19:34:04 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:34:04 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:34:04 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:34:04 INFO] [run:323][39m Running experiment: What happens if we abort responses
[36m[2021-04-12 19:34:04 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-12 19:34:04 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:06 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/d69e47d9-fa87-4e03-a0cb-22ab3daf43dd
[36m[2021-04-12 19:34:06 DEBUG] [workspace:147][39m Registering experiment 'abort-failure-mg.yaml' with ID '1f4a644c-ca52-4f9f-97cb-fb76c97bf39b' for organization '846e69e0-c776-46c9-a431-a7de0487556e' and team 'ad7ea2e6-37e0-4421-b763-73bb5a55dd9f'
[36m[2021-04-12 19:34:06 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-04-12 19:34:06 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-12 19:34:06 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-12 19:34:06 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-12 19:34:06 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:34:06 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:09 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-12 19:34:09 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-12 19:34:09 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:34:09 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:10 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:10 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:12 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:34:12 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '14', 'date': 'Mon, 12 Apr 2021 17:34:12 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:34:12 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:12 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:13 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:34:13 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:13 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:15 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:34:15 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Mon, 12 Apr 2021 17:34:15 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:34:15 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:15 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:17 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:34:17 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:17 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:18 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:34:18 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '11', 'date': 'Mon, 12 Apr 2021 17:34:18 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:34:18 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:18 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:20 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:34:20 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:20 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:22 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:34:22 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Mon, 12 Apr 2021 17:34:22 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:34:22 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:22 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:23 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:34:23 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:23 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:25 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:34:25 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '12', 'date': 'Mon, 12 Apr 2021 17:34:25 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:34:25 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:25 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:26 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-12 19:34:26 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-12 19:34:26 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:34:26 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:28 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-12 19:34:28 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:34:28 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:30 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:30 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:34:31 INFO] [activity:161][39m Action: abort-failure
[36m[2021-04-12 19:34:31 DEBUG] [python:34][39m Activity 'abort-failure' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-12 19:34:31 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-12 19:34:31 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 228, in add_abort_fault
        return set_fault(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 45, in set_fault
        (destination["host"], destination["subset"]))
    KeyError: 'subset'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 228, in add_abort_fault
        return set_fault(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 45, in set_fault
        (destination["host"], destination["subset"]))
    chaoslib.exceptions.ActivityFailed: KeyError: 'subset'
[31m[2021-04-12 19:34:31 ERROR] [activity:188][39m   => failed: KeyError: 'subset'
[32m[2021-04-12 19:34:31 INFO] [activity:198][39m Pausing after activity for 10s...
[36m[2021-04-12 19:34:36 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:34:36 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:37 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:34:37 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[33m[2021-04-12 19:34:39 WARNING] [run:390][39m Received a termination signal (Ctrl-C)...
[32m[2021-04-12 19:34:39 INFO] [run:421][39m Experiment ended with status: interrupted
[36m[2021-04-12 19:34:39 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:34:39 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:34:42 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-12 19:34:42 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-12 19:34:42 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-12 19:34:42 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-12 19:38:36 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-12 19:38:36 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-12 19:38:36 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-12 19:38:37 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-12 19:38:37 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:38:37 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:37 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:38:37 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:37 DEBUG] [controls:109][39m Using experiment ID 1f4a644c-ca52-4f9f-97cb-fb76c97bf39b from workspace for experiment at location abort-failure-mg.yaml
[36m[2021-04-12 19:38:37 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:38:37 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-12 19:38:37 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-12 19:38:37 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:38:37 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:38:37 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:38:37 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-12 19:38:37 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-12 19:38:37 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:38:37 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-12 19:38:37 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:38:37 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:38:37 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:38:37 INFO] [run:323][39m Running experiment: What happens if we abort responses
[36m[2021-04-12 19:38:37 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-12 19:38:37 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:39 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/9e81dbbd-1b4b-42d8-97e0-0ee74270f217
[36m[2021-04-12 19:38:39 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-04-12 19:38:39 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-12 19:38:39 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-12 19:38:39 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-12 19:38:39 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:38:39 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:41 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-12 19:38:41 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-12 19:38:41 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:38:41 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:43 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:43 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:44 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:38:44 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '15', 'date': 'Mon, 12 Apr 2021 17:38:44 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:38:44 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:44 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:46 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:38:46 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:46 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:47 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:38:48 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '23', 'date': 'Mon, 12 Apr 2021 17:38:47 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:38:48 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:48 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:49 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:38:49 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:49 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:51 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:38:51 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '17', 'date': 'Mon, 12 Apr 2021 17:38:50 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:38:51 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:51 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:52 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:38:52 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:52 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:54 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:38:54 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '22', 'date': 'Mon, 12 Apr 2021 17:38:53 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:38:54 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:54 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:55 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:38:55 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:55 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:38:57 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:38:57 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '6', 'date': 'Mon, 12 Apr 2021 17:38:56 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:38:57 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:38:57 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:38:58 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-12 19:38:58 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-12 19:38:58 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:38:58 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:00 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-12 19:39:00 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:39:00 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:02 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:02 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:03 INFO] [activity:161][39m Action: abort-failure
[36m[2021-04-12 19:39:03 DEBUG] [python:34][39m Activity 'abort-failure' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-12 19:39:03 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-12 19:39:03 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 228, in add_abort_fault
        return set_fault(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 45, in set_fault
        (destination["host"], destination["subset"]))
    KeyError: 'subset'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 228, in add_abort_fault
        return set_fault(
      File "/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py", line 45, in set_fault
        (destination["host"], destination["subset"]))
    chaoslib.exceptions.ActivityFailed: KeyError: 'subset'
[31m[2021-04-12 19:39:03 ERROR] [activity:188][39m   => failed: KeyError: 'subset'
[32m[2021-04-12 19:39:03 INFO] [activity:198][39m Pausing after activity for 10s...
[36m[2021-04-12 19:39:13 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:13 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:15 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:39:15 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:17 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-12 19:39:17 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-12 19:39:17 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:39:17 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:18 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:18 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:20 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:39:20 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '8', 'date': 'Mon, 12 Apr 2021 17:39:20 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:39:20 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:20 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:21 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:39:21 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:21 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:23 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:39:23 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '13', 'date': 'Mon, 12 Apr 2021 17:39:23 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:39:23 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:23 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:24 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:39:24 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:24 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:26 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:39:26 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '11', 'date': 'Mon, 12 Apr 2021 17:39:26 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:39:26 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:26 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:27 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:39:27 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:27 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:29 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:39:29 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '22', 'date': 'Mon, 12 Apr 2021 17:39:29 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:39:29 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:29 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:31 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:39:31 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:31 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:32 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:39:32 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '24', 'date': 'Mon, 12 Apr 2021 17:39:32 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:39:32 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:39:32 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:34 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-12 19:39:34 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-12 19:39:34 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:39:34 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:36 INFO] [run:809][39m Let's rollback...
[36m[2021-04-12 19:39:36 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-12 19:39:36 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:37 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-04-12 19:39:37 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-04-12 19:39:37 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:39:39 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-04-12 19:39:39 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:39:39 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:39:41 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-12 19:39:41 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-12 19:39:41 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-12 19:39:41 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-12 19:46:27 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-12 19:46:27 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-12 19:46:27 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-12 19:46:28 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-12 19:46:28 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:46:28 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:28 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-12 19:46:28 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:28 DEBUG] [controls:109][39m Using experiment ID 1f4a644c-ca52-4f9f-97cb-fb76c97bf39b from workspace for experiment at location abort-failure-mg.yaml
[36m[2021-04-12 19:46:28 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:46:28 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-12 19:46:28 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-12 19:46:28 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:46:28 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:46:28 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:46:28 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-12 19:46:28 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-12 19:46:28 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-12 19:46:28 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-12 19:46:28 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-12 19:46:28 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-12 19:46:28 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-12 19:46:28 INFO] [run:323][39m Running experiment: What happens if we abort responses
[36m[2021-04-12 19:46:28 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-12 19:46:28 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:31 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/b2934029-064d-42e2-82eb-2a192ec762e8
[36m[2021-04-12 19:46:31 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-04-12 19:46:31 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-12 19:46:31 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-12 19:46:31 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-12 19:46:31 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:46:31 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:33 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-12 19:46:33 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-12 19:46:33 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:46:33 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:34 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:34 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:36 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:46:36 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '26', 'date': 'Mon, 12 Apr 2021 17:46:36 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:46:36 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:36 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:37 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:46:37 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:37 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:39 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:46:39 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Mon, 12 Apr 2021 17:46:39 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:46:39 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:39 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:41 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:46:41 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:41 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:42 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:46:42 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '10', 'date': 'Mon, 12 Apr 2021 17:46:42 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:46:42 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:42 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:44 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:46:44 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:44 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:46 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:46:46 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '9', 'date': 'Mon, 12 Apr 2021 17:46:45 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:46:46 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:46 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:47 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:46:47 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:47 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:49 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:46:49 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '11', 'date': 'Mon, 12 Apr 2021 17:46:48 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:46:49 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:49 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:50 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-12 19:46:50 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-12 19:46:50 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:46:50 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:52 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-12 19:46:52 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:46:52 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:46:53 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:46:53 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:46:55 INFO] [activity:161][39m Action: abort-failure
[36m[2021-04-12 19:46:55 DEBUG] [python:34][39m Activity 'abort-failure' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-12 19:46:55 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-12 19:46:55 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-12 19:46:55 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"httpbin","namespace":"default"},"spec":{"gateways":["ingress-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/mg"}}],"rewrite":{"uri":" "},"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]},{"match":[{"uri":{"prefix":"/read"}}],"rewrite":{"uri":" "},"route":[{"destination":{"host":"ms-read","port":{"number":8088},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-12T15:32:21Z', 'generation': 3, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:gateways': {}, 'f:hosts': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-12T15:32:21Z'}, {'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:http': {}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-04-12T17:46:55Z'}], 'name': 'httpbin', 'namespace': 'default', 'resourceVersion': '11227', 'uid': '7a46fdd0-d0bf-4c4c-8512-76f80cff3399'}, 'spec': {'gateways': ['ingress-gateway'], 'hosts': ['*'], 'http': [{'fault': {'abort': {'httpStatus': 500, 'percentage': {'value': 50}}}, 'match': [{'uri': {'prefix': '/mg'}}], 'rewrite': {'uri': ' '}, 'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}, {'match': [{'uri': {'prefix': '/read'}}], 'rewrite': {'uri': ' '}, 'route': [{'destination': {'host': 'ms-read', 'port': {'number': 8088}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ff78395c-7811-4ae4-84a3-a7bf314af415', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'fa4de42a-8bf4-4763-883a-51e645f95065', 'Date': 'Mon, 12 Apr 2021 17:46:55 GMT', 'Content-Length': '1846'}}'
[32m[2021-04-12 19:46:55 INFO] [activity:198][39m Pausing after activity for 10s...
[36m[2021-04-12 19:47:05 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:05 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:07 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-12 19:47:07 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:08 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-12 19:47:08 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-12 19:47:08 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:47:08 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:10 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:10 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:47:11 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:47:11 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '19', 'date': 'Mon, 12 Apr 2021 17:47:11 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:47:11 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:11 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:13 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:47:13 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:13 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:47:15 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:47:15 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '21', 'date': 'Mon, 12 Apr 2021 17:47:14 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-12 19:47:15 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:15 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:16 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:47:16 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:16 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-12 19:47:18 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-12 19:47:18 DEBUG] [activity:180][39m   => succeeded with '{'status': 500, 'headers': {'content-length': '18', 'content-type': 'text/plain', 'date': 'Mon, 12 Apr 2021 17:47:17 GMT', 'server': 'istio-envoy'}, 'body': 'fault filter abort'}'
[36m[2021-04-12 19:47:18 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-12 19:47:18 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:19 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-12 19:47:19 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-12 19:47:19 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[31m[2021-04-12 19:47:21 CRITICAL] [run:507][39m Steady state probe 'app-responds-to-requests' is not in the given tolerance so failing this experiment
[32m[2021-04-12 19:47:21 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-12 19:47:21 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-12 19:47:21 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-12 19:47:21 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-12 19:47:23 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-12 19:47:23 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-12 19:47:23 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-12 19:47:23 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-13 08:58:41 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-13 08:58:41 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-13 08:58:41 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-13 08:58:43 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-13 08:58:43 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-13 08:58:43 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:43 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-13 08:58:43 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:43 DEBUG] [controls:109][39m Using experiment ID 1f4a644c-ca52-4f9f-97cb-fb76c97bf39b from workspace for experiment at location abort-failure-mg.yaml
[36m[2021-04-13 08:58:43 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-13 08:58:43 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-04-13 08:58:43 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-04-13 08:58:43 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-13 08:58:43 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-13 08:58:43 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-13 08:58:45 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-04-13 08:58:45 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-13 08:58:45 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-04-13 08:58:45 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-04-13 08:58:45 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-04-13 08:58:45 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-04-13 08:58:45 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-04-13 08:58:45 INFO] [run:323][39m Running experiment: What happens if we abort responses
[36m[2021-04-13 08:58:45 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-04-13 08:58:45 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:58:47 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/7a1ba0e0-f14e-45d6-8e98-ce291aab5290
[36m[2021-04-13 08:58:47 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-04-13 08:58:47 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-04-13 08:58:47 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-04-13 08:58:47 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-04-13 08:58:47 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-13 08:58:47 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:49 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-04-13 08:58:49 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-13 08:58:49 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-13 08:58:49 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:51 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:51 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:58:52 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:58:52 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Tue, 13 Apr 2021 06:58:52 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-13 08:58:52 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:52 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:54 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-13 08:58:54 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:54 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:58:56 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:58:56 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '22', 'date': 'Tue, 13 Apr 2021 06:58:55 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-13 08:58:56 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:56 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:58:57 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-13 08:58:57 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:57 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:58:59 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:58:59 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '25', 'date': 'Tue, 13 Apr 2021 06:58:59 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-13 08:58:59 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:58:59 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:00 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-13 08:59:00 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:00 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:59:02 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:59:02 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '7', 'date': 'Tue, 13 Apr 2021 06:59:02 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-13 08:59:02 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:02 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:04 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-13 08:59:04 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:04 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:59:05 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:59:05 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '25', 'date': 'Tue, 13 Apr 2021 06:59:05 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-04-13 08:59:05 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:05 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:07 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-04-13 08:59:07 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-04-13 08:59:07 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-13 08:59:07 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:59:08 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-04-13 08:59:08 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-04-13 08:59:08 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:10 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:10 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:59:12 INFO] [activity:161][39m Action: abort-failure
[36m[2021-04-13 08:59:12 DEBUG] [python:34][39m Activity 'abort-failure' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosistio/fault/actions.py'
[36m[2021-04-13 08:59:12 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-13 08:59:12 DEBUG] [__init__:67][39m Using Kubernetes context: default
[36m[2021-04-13 08:59:12 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'body': {'apiVersion': 'networking.istio.io/v1alpha3', 'kind': 'VirtualService', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"httpbin","namespace":"default"},"spec":{"gateways":["ingress-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/mg"}}],"retries":{"attempts":10,"perTryTimeout":"3s","retryOn":"5xx"},"rewrite":{"uri":" "},"route":[{"destination":{"host":"mg-v1","port":{"number":8081},"subset":"primary"}}]},{"match":[{"uri":{"prefix":"/read"}}],"retries":{"attempts":10,"perTryTimeout":"3s","retryOn":"5xx"},"rewrite":{"uri":" "},"route":[{"destination":{"host":"ms-read","port":{"number":8088},"subset":"primary"}}]}]}}\n'}, 'creationTimestamp': '2021-04-13T06:56:36Z', 'generation': 2, 'managedFields': [{'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-applied-configuration': {}}}, 'f:spec': {'.': {}, 'f:gateways': {}, 'f:hosts': {}}}, 'manager': 'kubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-13T06:56:36Z'}, {'apiVersion': 'networking.istio.io/v1alpha3', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:http': {}}}, 'manager': 'OpenAPI-Generator', 'operation': 'Update', 'time': '2021-04-13T06:59:12Z'}], 'name': 'httpbin', 'namespace': 'default', 'resourceVersion': '15646', 'uid': '9de6770c-f005-4302-bd8c-12a2e46fb698'}, 'spec': {'gateways': ['ingress-gateway'], 'hosts': ['*'], 'http': [{'fault': {'abort': {'httpStatus': 500, 'percentage': {'value': 50}}}, 'match': [{'uri': {'prefix': '/mg'}}], 'retries': {'attempts': 10, 'perTryTimeout': '3s', 'retryOn': '5xx'}, 'rewrite': {'uri': ' '}, 'route': [{'destination': {'host': 'mg-v1', 'port': {'number': 8081}, 'subset': 'primary'}}]}, {'match': [{'uri': {'prefix': '/read'}}], 'retries': {'attempts': 10, 'perTryTimeout': '3s', 'retryOn': '5xx'}, 'rewrite': {'uri': ' '}, 'route': [{'destination': {'host': 'ms-read', 'port': {'number': 8088}, 'subset': 'primary'}}]}]}}, 'headers': {'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'ff78395c-7811-4ae4-84a3-a7bf314af415', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'fa4de42a-8bf4-4763-883a-51e645f95065', 'Date': 'Tue, 13 Apr 2021 06:59:12 GMT', 'Transfer-Encoding': 'chunked'}}'
[32m[2021-04-13 08:59:12 INFO] [activity:198][39m Pausing after activity for 10s...
[36m[2021-04-13 08:59:22 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:22 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:23 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-04-13 08:59:23 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:25 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-04-13 08:59:25 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-04-13 08:59:25 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-13 08:59:25 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:26 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:26 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-04-13 08:59:28 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-04-13 08:59:28 DEBUG] [activity:180][39m   => succeeded with '{'status': 500, 'headers': {'content-length': '18', 'content-type': 'text/plain', 'date': 'Tue, 13 Apr 2021 06:59:28 GMT', 'server': 'istio-envoy'}, 'body': 'fault filter abort'}'
[36m[2021-04-13 08:59:28 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-04-13 08:59:28 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:30 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[36m[2021-04-13 08:59:30 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-04-13 08:59:30 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[31m[2021-04-13 08:59:31 CRITICAL] [run:507][39m Steady state probe 'app-responds-to-requests' is not in the given tolerance so failing this experiment
[32m[2021-04-13 08:59:31 INFO] [run:421][39m Experiment ended with status: deviated
[32m[2021-04-13 08:59:31 INFO] [run:423][39m The steady-state has deviated, a weakness may have been discovered
[36m[2021-04-13 08:59:31 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-04-13 08:59:31 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 08:59:34 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-04-13 08:59:34 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-04-13 08:59:34 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-04-13 08:59:34 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-04-13 09:04:14 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-04-13 09:04:14 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-04-13 09:04:14 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-04-13 09:04:15 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-04-13 09:04:15 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-13 09:04:15 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-04-13 09:04:15 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-04-13 09:04:15 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[31m[2021-04-13 09:04:15 ERROR] [cli:164][39m Path "abort-failure-mg.yaml" does not exist.
[36m[2021-04-13 09:04:15 DEBUG] [cli:165][39m Path "abort-failure-mg.yaml" does not exist.
