[36m[2021-05-01 22:33:09 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-05-01 22:33:09 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-05-01 22:33:09 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-05-01 22:33:09 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-05-01 22:33:09 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:33:09 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:09 DEBUG] [workspace:85][39m The ChaosIQ workspace file could not be found at '.chaosiq'.
[36m[2021-05-01 22:33:09 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:33:09 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:09 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:33:09 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-05-01 22:33:09 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-05-01 22:33:09 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:33:09 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:33:09 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:33:15 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-05-01 22:33:15 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-01 22:33:15 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:33:15 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-05-01 22:33:15 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:33:15 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:33:15 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:33:15 INFO] [run:323][39m Running experiment: What happens if we terminate an instance of the application?
[36m[2021-05-01 22:33:15 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-05-01 22:33:15 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:17 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/ec1fd487-1e5e-4914-a1e9-0e1684a84127
[36m[2021-05-01 22:33:17 DEBUG] [workspace:147][39m Registering experiment 'healthy-read-pod.yaml' with ID '0e362782-9627-4a19-bcce-51b6db09d8f8' for organization '846e69e0-c776-46c9-a431-a7de0487556e' and team 'ad7ea2e6-37e0-4421-b763-73bb5a55dd9f'
[36m[2021-05-01 22:33:17 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-05-01 22:33:17 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-05-01 22:33:17 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-05-01 22:33:17 INFO] [run:345][39m Rollbacks strategy: always
[36m[2021-05-01 22:33:17 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:33:17 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:23 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-05-01 22:33:23 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:33:23 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:33:23 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:25 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:25 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:27 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:33:27 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '323', 'x-envoy-upstream-service-time': '48', 'date': 'Sat, 01 May 2021 20:33:27 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        }\n    ]\n}'}'
[36m[2021-05-01 22:33:27 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:27 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:28 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:33:28 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:33:28 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:33:28 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:30 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-05-01 22:33:30 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:33:30 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:31 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:31 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:33 INFO] [activity:161][39m Probe: read-pod-logs
[36m[2021-05-01 22:33:33 DEBUG] [python:34][39m Activity 'read-pod-logs' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-05-01 22:33:33 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-05-01 22:33:34 DEBUG] [probes:53][39m Found 0 pods: [] in ns 'default'
[36m[2021-05-01 22:33:34 DEBUG] [activity:180][39m   => succeeded with '{}'
[32m[2021-05-01 22:33:34 INFO] [activity:198][39m Pausing after activity for 2s...
[36m[2021-05-01 22:33:36 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:36 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:37 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:33:37 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:39 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-05-01 22:33:39 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:33:39 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:33:39 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:40 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:40 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:42 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:33:42 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '323', 'x-envoy-upstream-service-time': '51', 'date': 'Sat, 01 May 2021 20:33:42 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        }\n    ]\n}'}'
[36m[2021-05-01 22:33:42 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:33:42 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:44 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:33:44 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:33:44 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:33:44 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[33m[2021-05-01 22:33:45 WARNING] [run:580][39m Rollbacks were explicitly requested to be played
[32m[2021-05-01 22:33:45 INFO] [run:809][39m Let's rollback...
[36m[2021-05-01 22:33:45 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:33:45 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:47 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-05-01 22:33:47 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:33:47 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:33:48 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-05-01 22:33:48 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:33:48 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:33:50 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-05-01 22:33:50 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-05-01 22:33:50 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-05-01 22:33:50 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-01 22:38:23 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-05-01 22:38:23 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-05-01 22:38:23 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-05-01 22:38:24 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-05-01 22:38:24 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:38:24 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:24 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:38:24 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:24 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:38:24 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-05-01 22:38:24 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-05-01 22:38:24 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:38:24 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:38:24 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:38:25 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-05-01 22:38:25 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-01 22:38:25 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:38:25 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-05-01 22:38:25 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:38:25 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:38:25 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:38:25 INFO] [run:323][39m Running experiment: What happens if we terminate an instance of the application?
[36m[2021-05-01 22:38:25 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-05-01 22:38:25 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:27 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/d1dfa890-c574-4267-bd78-f1ae54c31e3d
[36m[2021-05-01 22:38:27 DEBUG] [workspace:147][39m Registering experiment 'healthy-mg-pod.yaml' with ID 'c32a18ac-5c1e-4748-97fc-26fe32933869' for organization '846e69e0-c776-46c9-a431-a7de0487556e' and team 'ad7ea2e6-37e0-4421-b763-73bb5a55dd9f'
[36m[2021-05-01 22:38:27 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-05-01 22:38:27 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-05-01 22:38:27 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-05-01 22:38:27 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-05-01 22:38:27 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:38:27 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:29 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-05-01 22:38:29 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:38:29 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:38:29 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:30 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:30 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:32 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:38:32 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '71', 'date': 'Sat, 01 May 2021 20:38:32 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-05-01 22:38:32 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:32 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:33 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:38:33 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:38:33 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:38:33 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:35 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-05-01 22:38:35 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:38:35 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:37 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:37 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:38 INFO] [activity:161][39m Probe: read-pod-logs
[36m[2021-05-01 22:38:38 DEBUG] [python:34][39m Activity 'read-pod-logs' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[36m[2021-05-01 22:38:38 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-05-01 22:38:38 DEBUG] [probes:53][39m Found 0 pods: [] in ns 'default'
[36m[2021-05-01 22:38:38 DEBUG] [activity:180][39m   => succeeded with '{}'
[32m[2021-05-01 22:38:38 INFO] [activity:198][39m Pausing after activity for 2s...
[36m[2021-05-01 22:38:40 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:40 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:42 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:38:42 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:44 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-05-01 22:38:44 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:38:44 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:38:44 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:45 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:45 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:47 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:38:47 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '24', 'date': 'Sat, 01 May 2021 20:38:47 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-05-01 22:38:47 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:38:47 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:49 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:38:49 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:38:49 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:38:49 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:50 INFO] [run:809][39m Let's rollback...
[36m[2021-05-01 22:38:50 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:38:50 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:52 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-05-01 22:38:52 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:38:52 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:38:53 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-05-01 22:38:53 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:38:53 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:38:55 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-05-01 22:38:55 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-05-01 22:38:55 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-05-01 22:38:55 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-01 22:46:33 DEBUG] [cli:73][39m ###############################################################################
[36m[2021-05-01 22:46:33 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-05-01 22:46:33 DEBUG] [cli:78][39m Using settings file '/home/luisreciomelero/.chaostoolkit/settings.yaml'
[36m[2021-05-01 22:46:34 DEBUG] [__init__:167][39m Loading global control 'chaosiq-cloud'
[36m[2021-05-01 22:46:34 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:46:34 DEBUG] [python:166][39m Control 'before_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:34 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'loader'
[36m[2021-05-01 22:46:34 DEBUG] [python:166][39m Control 'after_loading_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:34 DEBUG] [controls:109][39m Using experiment ID c32a18ac-5c1e-4748-97fc-26fe32933869 from workspace for experiment at location healthy-mg-pod.yaml
[36m[2021-05-01 22:46:34 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:46:34 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-05-01 22:46:34 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-05-01 22:46:34 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:46:34 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:46:34 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:46:34 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-05-01 22:46:34 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-01 22:46:34 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-01 22:46:34 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-05-01 22:46:34 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-01 22:46:34 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-01 22:46:34 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-01 22:46:34 INFO] [run:323][39m Running experiment: What happens if we terminate an instance of the application?
[36m[2021-05-01 22:46:34 DEBUG] [__init__:136][39m Initializing global control 'chaosiq-cloud'
[36m[2021-05-01 22:46:34 DEBUG] [python:166][39m Control 'configure_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:46:37 INFO] [execution:64][39m Execution available at http://console.chaosiq.io/tfm/luisreciomelero/executions/61b7d89d-a223-45be-8695-1d8a42d4b5da
[36m[2021-05-01 22:46:37 DEBUG] [workspace:108][39m Saving workspace at .chaosiq
[36m[2021-05-01 22:46:37 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-05-01 22:46:37 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-05-01 22:46:37 INFO] [run:345][39m Rollbacks strategy: default
[36m[2021-05-01 22:46:37 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:46:37 DEBUG] [python:166][39m Control 'before_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:38 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-05-01 22:46:38 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:46:38 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:46:38 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:40 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:40 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:46:41 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:46:41 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '28', 'date': 'Sat, 01 May 2021 20:46:41 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-05-01 22:46:41 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:41 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:43 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:46:43 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:46:43 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:46:43 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:46:45 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-05-01 22:46:45 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:46:45 DEBUG] [python:166][39m Control 'before_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:46 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:46 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:46:48 INFO] [activity:161][39m Action: terminate-app-pod
[36m[2021-05-01 22:46:48 DEBUG] [python:34][39m Activity 'terminate-app-pod' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[36m[2021-05-01 22:46:48 DEBUG] [__init__:65][39m Using Kubernetes context: default
[36m[2021-05-01 22:46:48 DEBUG] [actions:193][39m Found 2 pods labelled 'app=mg-backend' in ns default
[36m[2021-05-01 22:46:48 DEBUG] [activity:182][39m   => succeeded without any result value
[32m[2021-05-01 22:46:48 INFO] [activity:198][39m Pausing after activity for 2s...
[36m[2021-05-01 22:46:50 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:50 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:52 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'method'
[36m[2021-05-01 22:46:52 DEBUG] [python:166][39m Control 'after_method_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:53 DEBUG] [run:496][39m Running steady-state hypothesis after the method
[32m[2021-05-01 22:46:53 INFO] [hypothesis:183][39m Steady state hypothesis: The app is healthy
[36m[2021-05-01 22:46:53 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:46:53 DEBUG] [python:166][39m Control 'before_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:55 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:55 DEBUG] [python:166][39m Control 'before_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:46:57 INFO] [activity:161][39m Probe: app-responds-to-requests
[36m[2021-05-01 22:46:57 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'content-type': 'application/json; charset=UTF-8', 'content-length': '1284', 'x-envoy-upstream-service-time': '49', 'date': 'Sat, 01 May 2021 20:46:56 GMT', 'server': 'istio-envoy'}, 'body': '\n{\n    "status": "UP",\n    "checks": [\n        {\n            "name": "Liveness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - liveness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        },\n        {\n            "name": "Database connections health check",\n            "status": "UP"\n        },\n        {\n            "name": "Readiness check",\n            "status": "UP"\n        },\n        {\n            "name": "SmallRye Reactive Messaging - readiness check",\n            "status": "UP",\n            "data": {\n                "usuarios-delete": "[OK]",\n                "usuarios-sendemail": "[OK]",\n                "usuarios-sendnotification": "[OK]",\n                "usuarios-create": "[OK]",\n                "handlednotification-usuarios": "[OK]",\n                "usuarios-update": "[OK]",\n                "usuarios-sendsms": "[OK]"\n            }\n        }\n    ]\n}'}'
[36m[2021-05-01 22:46:57 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'activity'
[36m[2021-05-01 22:46:57 DEBUG] [python:166][39m Control 'after_activity_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:46:58 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-01 22:46:58 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-01 22:46:58 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'hypothesis'
[36m[2021-05-01 22:46:58 DEBUG] [python:166][39m Control 'after_hypothesis_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:47:00 INFO] [run:809][39m Let's rollback...
[36m[2021-05-01 22:47:00 DEBUG] [__init__:365][39m Applying before-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:47:00 DEBUG] [python:166][39m Control 'before_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:47:01 INFO] [rollback:25][39m No declared rollbacks, let's move on.
[36m[2021-05-01 22:47:01 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'rollback'
[36m[2021-05-01 22:47:01 DEBUG] [python:166][39m Control 'after_rollback_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[32m[2021-05-01 22:47:03 INFO] [run:421][39m Experiment ended with status: completed
[36m[2021-05-01 22:47:03 DEBUG] [__init__:365][39m Applying after-control 'chaosiq-cloud' on 'experiment'
[36m[2021-05-01 22:47:03 DEBUG] [python:166][39m Control 'after_experiment_control' loaded from '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py'
[36m[2021-05-01 22:47:05 DEBUG] [__init__:72][39m Cleaning up controls
[36m[2021-05-01 22:47:05 DEBUG] [__init__:188][39m Cleaning up global control 'chaosiq-cloud'
[36m[2021-05-01 22:47:05 DEBUG] [python:159][39m Control module '/home/luisreciomelero/.local/lib/python3.8/site-packages/chaoscloud/controls.py' does not declare 'cleanup_control'
[36m[2021-05-01 22:47:05 DEBUG] [caching:42][39m Clearing activities cache
